// Bundles src/extension.ts into one dist/extension.js, and writes the
// generated pairing module the bundle imports.
//
// One bundle is VS Code's own guidance and it keeps activation cheap: the
// extension host reads one file instead of walking a node_modules tree.

import { build, context } from "esbuild";
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");

/**
 * The dinah release this build of the extension was cut alongside.
 *
 * A release run passes the tag it reserved through DINAH_PAIRED_RELEASE. A
 * local build has no tag, and says "source" rather than inventing one, because
 * a made-up tag in a diagnostic is worse than an honest absence.
 *
 * This value is displayed and never compared. What is compared is the storage
 * format and the conformance profile the binary reports at run time, which is
 * the only pair that says whether the two can actually work together.
 */
function pairedRelease() {
	const declared = process.env.DINAH_PAIRED_RELEASE;
	if (declared && declared.trim() !== "") {
		return declared.trim();
	}
	return "source";
}

function generate() {
	const dir = join(here, "src", "generated");
	mkdirSync(dir, { recursive: true });
	const body = [
		"// Generated by esbuild.mjs. Not committed, not edited by hand.",
		"",
		"/** The dinah release this build of the extension was cut alongside. */",
		`export const PAIRED_RELEASE = ${JSON.stringify(pairedRelease())};`,
		"",
	].join("\n");
	writeFileSync(join(dir, "pairing.ts"), body, "utf8");
}

/** Reports the git commit this build came from, or "unknown" outside a checkout. */
export function describeCommit() {
	try {
		return execFileSync("git", ["-C", repoRoot, "rev-parse", "--short", "HEAD"], {
			encoding: "utf8",
		}).trim();
	} catch {
		return "unknown";
	}
}

const options = {
	entryPoints: [join(here, "src", "extension.ts")],
	bundle: true,
	format: "cjs",
	platform: "node",
	target: "node20",
	outfile: join(here, "dist", "extension.js"),
	external: ["vscode"],
	minify: process.env.NODE_ENV === "production",
	sourcemap: process.env.NODE_ENV !== "production",
	logLevel: "info",
};

generate();

if (process.argv.includes("--generate-only")) {
	// Nothing else to do: check-types and compile-tests both need the
	// generated module to exist and neither of them wants a bundle.
} else if (process.argv.includes("--watch")) {
	const ctx = await context(options);
	await ctx.watch();
} else {
	await build(options);
}
