package perfstore

// words is the fixed list every generated text is drawn from. It holds exactly
// 256 entries, so one byte of a SHA-256 draw picks one word with no bias, and
// every entry is lowercase ASCII with no space and no newline, which is what
// lets a journal event carry a text drawn from it without the normalisation
// bench.AppendEvent would otherwise apply.
//
// Changing an entry changes every generated byte and so every digest, which is
// the determinism guarantee working as stated: the guarantee is over one
// source tree, and this list is part of the tree.
var words = [...]string{
	"about", "above", "accept", "account", "across", "action", "active", "actor",
	"after", "again", "agent", "agree", "ahead", "allow", "alone", "along",
	"amend", "anchor", "answer", "append", "apply", "archive", "argue", "arrive",
	"aside", "attach", "audit", "author", "avoid", "await", "backlog", "badge",
	"basis", "batch", "before", "begin", "behind", "below", "margin", "binary",
	"block", "board", "body", "boundary", "branch", "brief", "budget", "build",
	"cache", "call", "card", "carry", "cause", "change", "check", "choice",
	"claim", "clean", "clear", "client", "close", "column", "command", "comment",
	"commit", "compose", "confirm", "contract", "copy", "count", "cover", "create",
	"current", "cursor", "cycle", "daily", "data", "date", "decide", "decision",
	"declare", "default", "defect", "define", "delete", "deliver", "depend", "design",
	"detail", "digest", "direct", "disk", "divide", "document", "done", "draft",
	"empty", "enable", "entity", "entry", "equal", "error", "event", "every",
	"exact", "exist", "expect", "export", "fact", "fail", "field", "file",
	"filter", "final", "find", "first", "fixture", "flag", "flow", "follow",
	"format", "forward", "found", "frame", "fresh", "gate", "given", "grant",
	"guard", "handle", "harness", "head", "header", "history", "hold", "idle",
	"import", "index", "inside", "intake", "item", "journal", "judge", "keep",
	"label", "later", "layer", "leave", "legal", "level", "limit", "line",
	"link", "list", "local", "lock", "loop", "main", "mark", "match",
	"measure", "median", "member", "merge", "method", "model", "mount", "move",
	"name", "narrow", "never", "next", "note", "notice", "object", "offer",
	"open", "operator", "order", "other", "owner", "page", "parse", "path",
	"payload", "pending", "place", "plain", "point", "position", "prefix", "probe",
	"prose", "pull", "push", "query", "queue", "quiet", "range", "read",
	"ready", "reason", "record", "refuse", "release", "remote", "render", "repair",
	"reply", "report", "request", "resolve", "result", "review", "revision", "route",
	"rule", "runner", "scheme", "search", "second", "seed", "serve", "settle",
	"shape", "show", "signal", "slack", "slug", "source", "spec", "stage",
	"state", "status", "store", "stream", "table", "target", "test", "text",
	"tier", "timing", "title", "token", "trace", "tree", "trunk", "under",
	"update", "value", "verify", "view", "watch", "window", "word", "write",
}

// The blank declaration below fails to compile when the list above holds any
// number of entries other than 256. The length of an array is a constant, and
// a constant index into a one-element array is refused at compile time unless
// it is zero.
var _ = [1]struct{}{}[len(words)-256]
