//go:build ignore

// Command gen_emoji_properties writes emoji_properties.go from the published
// emoji-data.txt of UTS #51.
//
// It is a repository tool rather than a shipped command, because nobody
// outside this project generates one, and the build tag above keeps it out of
// the binary and out of `go build ./...`. Run it from the repository root:
//
//	go run internal/textwidth/gen_emoji_properties.go
//
// The input it reads is vendored beside it as emoji-data.txt, at the Unicode
// version named in unicodeVersion below. Nothing under golang.org/x/text and
// nothing in the standard library publishes a UTS #51 property, so the
// renderer cannot ask a library whether a run of runes draws as one emoji
// glyph and this table is what answers instead.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// unicodeVersion is the Unicode release the vendored emoji-data.txt was taken
// from. It has to agree with the standard library's own unicode.Version,
// because a table built at one release measures an emoji another release
// added from its parts instead of as one glyph. TestTheUnicodeTablesAgree in
// cmd/dinah is what fails when the two drift apart.
const unicodeVersion = "15.0.0"

// dataSource is where the vendored input came from, recorded in the generated
// file so a later regeneration fetches the same thing.
const dataSource = "https://www.unicode.org/Public/15.0.0/ucd/emoji/emoji-data.txt"

// wanted are the four properties the width rule reads, in the order the
// generated file declares them. Emoji says a code point can draw as an emoji
// at all, Emoji_Presentation says it draws that way with no request,
// Emoji_Modifier is the five skin tones, and Emoji_Modifier_Base is what a
// skin tone may attach to.
var wanted = []string{
	"Emoji",
	"Emoji_Presentation",
	"Emoji_Modifier",
	"Emoji_Modifier_Base",
}

// tableNames maps a property to the unexported Go identifier the generated
// file gives its range table.
var tableNames = map[string]string{
	"Emoji":               "emoji",
	"Emoji_Presentation":  "emojiPresentation",
	"Emoji_Modifier":      "emojiModifier",
	"Emoji_Modifier_Base": "emojiModifierBase",
}

// span is one inclusive code point range carrying one property.
type span struct {
	// lo and hi are the first and last code points of the range.
	lo, hi rune
}

func main() {
	dir := filepath.Join("internal", "textwidth")
	input := filepath.Join(dir, "emoji-data.txt")
	spans, err := read(input)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	body, err := render(spans)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	output := filepath.Join(dir, "emoji_properties.go")
	if err := os.WriteFile(output, []byte(body), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("wrote", output)
}

// read parses emoji-data.txt into the spans of each wanted property.
func read(path string) (map[string][]span, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	found := map[string][]span{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if cut := strings.IndexByte(line, '#'); cut >= 0 {
			line = line[:cut]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 {
			continue
		}
		property := strings.TrimSpace(fields[1])
		if _, ok := tableNames[property]; !ok {
			continue
		}
		lo, hi, err := parseRange(strings.TrimSpace(fields[0]))
		if err != nil {
			return nil, err
		}
		found[property] = append(found[property], span{lo: lo, hi: hi})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	for _, property := range wanted {
		if len(found[property]) == 0 {
			return nil, fmt.Errorf("%s: no ranges found, so the parse read nothing", property)
		}
	}
	return found, nil
}

// parseRange reads one code point or one `lo..hi` range of them.
func parseRange(field string) (rune, rune, error) {
	text := field
	high := field
	if cut := strings.Index(field, ".."); cut >= 0 {
		text = field[:cut]
		high = field[cut+2:]
	}
	lo, err := strconv.ParseUint(text, 16, 32)
	if err != nil {
		return 0, 0, err
	}
	hi, err := strconv.ParseUint(high, 16, 32)
	if err != nil {
		return 0, 0, err
	}
	return rune(lo), rune(hi), nil
}

// render composes the generated Go source.
func render(spans map[string][]span) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by gen_emoji_properties.go. DO NOT EDIT.\n\n")
	b.WriteString("package textwidth\n\n")
	b.WriteString("import \"unicode\"\n\n")
	b.WriteString("// EmojiUnicodeVersion is the Unicode release the tables below were\n")
	b.WriteString("// generated from. A caller comparing it against unicode.Version is what\n")
	b.WriteString("// catches a toolchain upgrade that moves the category tables and leaves\n")
	b.WriteString("// these behind.\n")
	b.WriteString("const EmojiUnicodeVersion = " + strconv.Quote(unicodeVersion) + "\n\n")
	b.WriteString("// emojiDataSource is where the vendored emoji-data.txt came from.\n")
	b.WriteString("const emojiDataSource = " + strconv.Quote(dataSource) + "\n")
	for _, property := range wanted {
		name := tableNames[property]
		merged := merge(spans[property])
		b.WriteString("\n// " + name + " holds every code point whose " + property + " property is Yes.\n")
		b.WriteString("var " + name + " = &unicode.RangeTable{\n")
		writeRanges(&b, merged)
		b.WriteString("}\n")
	}
	return b.String(), nil
}

// merge sorts spans and joins any that touch or overlap, so the generated
// table carries one entry per contiguous run.
func merge(in []span) []span {
	sorted := append([]span(nil), in...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].lo < sorted[j].lo })
	out := make([]span, 0, len(sorted))
	for _, s := range sorted {
		if len(out) > 0 && s.lo <= out[len(out)-1].hi+1 {
			if s.hi > out[len(out)-1].hi {
				out[len(out)-1].hi = s.hi
			}
			continue
		}
		out = append(out, s)
	}
	return out
}

// writeRanges writes the R16 and R32 members of one range table. A range
// straddling the 16-bit boundary is split, which is what unicode.RangeTable
// requires of its two slices.
func writeRanges(b *strings.Builder, spans []span) {
	var low, high []span
	for _, s := range spans {
		if s.hi <= 0xFFFF {
			low = append(low, s)
			continue
		}
		if s.lo <= 0xFFFF {
			low = append(low, span{lo: s.lo, hi: 0xFFFF})
			high = append(high, span{lo: 0x10000, hi: s.hi})
			continue
		}
		high = append(high, s)
	}
	if len(low) > 0 {
		b.WriteString("\tR16: []unicode.Range16{\n")
		for _, s := range low {
			fmt.Fprintf(b, "\t\t{Lo: 0x%04X, Hi: 0x%04X, Stride: 1},\n", s.lo, s.hi)
		}
		b.WriteString("\t},\n")
	}
	if len(high) > 0 {
		b.WriteString("\tR32: []unicode.Range32{\n")
		for _, s := range high {
			fmt.Fprintf(b, "\t\t{Lo: 0x%06X, Hi: 0x%06X, Stride: 1},\n", s.lo, s.hi)
		}
		b.WriteString("\t},\n")
	}
}
